<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\DesktopManager.Core\DesktopManager.Core.csproj" />
    <ProjectReference Include="..\DesktopManager.Native\DesktopManager.Native.csproj" />
    <ProjectReference Include="..\DesktopManager.Ipc\DesktopManager.Ipc.csproj" />
    <ProjectReference Include="..\DesktopManager.Player.Wallpaper\DesktopManager.Player.Wallpaper.csproj" />
    <ProjectReference Include="..\DesktopManager.Player.Icons\DesktopManager.Player.Icons.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="H.NotifyIcon.Wpf" Version="2.4.1" />
    <PackageReference Include="Serilog" Version="4.3.0" />
    <PackageReference Include="Serilog.Sinks.File" Version="6.0.0" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Assets\app.ico" />
  </ItemGroup>

  <PropertyGroup>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows10.0.19041.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

</Project>
