<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows10.0.19041.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <AssemblyName>DesktopManager.Plugin.Pet</AssemblyName>
    <RootNamespace>DesktopManager.Plugin.Pet</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\DesktopManager.Ipc\DesktopManager.Ipc.csproj" />
    <ProjectReference Include="..\Live2DCSharpSDK\Live2DCSharpSDK.OpenGL.WPF\Live2DCSharpSDK.OpenGL.WPF.csproj" />
  </ItemGroup>

  <ItemGroup>
  </ItemGroup>

  <ItemGroup>
    <None Include="Assets\live2d.html" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
